// mobile/src/components/StepIngredientLinker.tsx
import React, { useMemo, useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity } from 'react-native';
import { Ionicons, MaterialCommunityIcons } from '@expo/vector-icons';
import { Input } from './ui';
import { colors, spacing } from '../theme';

export interface LidIngredient {
  _lid: string;
  name: string;
  amount?: string;
  unit?: string;
}

// Faithful port of client/src/components/StepIngredientLinker.vue: three zones —
// linked chips, an "unassigned" worklist (ingredients mentioned in the step text
// float to the top), and a searchable browse-all list.
export default function StepIngredientLinker({
  value,
  ingredients,
  assignmentsById,
  stepNumber,
  stepText,
  onChange,
}: {
  value: string[];
  ingredients: LidIngredient[];
  assignmentsById: Record<string, number[]>;
  stepNumber: number;
  stepText: string;
  onChange: (lids: string[]) => void;
}) {
  const [showBrowse, setShowBrowse] = useState(false);
  const [query, setQuery] = useState('');

  const byId = useMemo(() => Object.fromEntries(ingredients.map((i) => [i._lid, i])), [ingredients]);
  const linked = value.map((lid) => byId[lid]).filter(Boolean) as LidIngredient[];
  const unassigned = ingredients.filter((i) => (assignmentsById[i._lid]?.length ?? 0) === 0);

  const rootWords = (name: string) =>
    String(name).toLowerCase().replace(/\(.*?\)/g, '').split(/\s+/).filter((w) => w.length > 2);
  const isMentioned = (ing: LidIngredient) => {
    const t = stepText.toLowerCase();
    return rootWords(ing.name).some((w) => t.includes(w));
  };
  const unassignedSorted = [...unassigned].sort((a, b) => Number(isMentioned(b)) - Number(isMentioned(a)));

  const browseList = useMemo(() => {
    const q = query.toLowerCase().trim();
    return q ? ingredients.filter((i) => i.name.toLowerCase().includes(q)) : ingredients;
  }, [query, ingredients]);

  const isLinked = (lid: string) => value.includes(lid);
  const amountLabel = (ing: LidIngredient) => [ing.amount, ing.unit].filter(Boolean).join(' ');
  const link = (lid: string) => !value.includes(lid) && onChange([...value, lid]);
  const unlink = (lid: string) => onChange(value.filter((x) => x !== lid));
  const toggle = (lid: string) => (isLinked(lid) ? unlink(lid) : link(lid));

  const statusOf = (ing: LidIngredient) => {
    const steps = assignmentsById[ing._lid] || [];
    if (isLinked(ing._lid)) {
      const others = steps.filter((s) => s !== stepNumber);
      return others.length ? `also step ${others.join(', ')}` : 'in this step';
    }
    return steps.length ? `step ${steps.join(', ')}` : 'unassigned';
  };

  return (
    <View style={styles.sil}>
      <Text style={styles.label}>In this step</Text>
      <View style={styles.chips}>
        {linked.length ? (
          linked.map((ing) => (
            <TouchableOpacity key={ing._lid} style={styles.linkedChip} onPress={() => unlink(ing._lid)}>
              {amountLabel(ing) ? <Text style={styles.amount}>{amountLabel(ing)} </Text> : null}
              <Text style={styles.linkedText}>{ing.name}</Text>
              <Ionicons name="close" size={13} color={colors.primary} />
            </TouchableOpacity>
          ))
        ) : (
          <Text style={styles.empty}>Nothing linked yet</Text>
        )}
      </View>

      <Text style={[styles.label, { marginTop: spacing.sm }]}>Unassigned</Text>
      <View style={styles.chips}>
        {unassigned.length ? (
          unassignedSorted.map((ing) => (
            <TouchableOpacity
              key={ing._lid}
              style={[styles.addChip, isMentioned(ing) && styles.addChipHot]}
              onPress={() => link(ing._lid)}
            >
              <MaterialCommunityIcons name={isMentioned(ing) ? 'creation' : 'plus'} size={13} color={isMentioned(ing) ? colors.warning : colors.textMuted} />
              <Text style={styles.addText}>{ing.name}</Text>
            </TouchableOpacity>
          ))
        ) : (
          <View style={styles.doneRow}>
            <Ionicons name="checkmark-circle" size={15} color={colors.success} />
            <Text style={styles.doneText}>Every ingredient is used in a step</Text>
          </View>
        )}
      </View>

      <TouchableOpacity style={styles.browseBtn} onPress={() => setShowBrowse((s) => !s)}>
        <Ionicons name={showBrowse ? 'chevron-up' : 'search'} size={14} color={colors.textMuted} />
        <Text style={styles.browseBtnText}>Browse all ingredients</Text>
      </TouchableOpacity>
      {showBrowse ? (
        <View style={styles.browseCard}>
          <Input value={query} onChangeText={setQuery} placeholder="Search…" />
          {browseList.map((ing) => (
            <TouchableOpacity key={ing._lid} style={styles.browseRow} onPress={() => toggle(ing._lid)}>
              <Ionicons
                name={isLinked(ing._lid) ? 'checkbox' : 'square-outline'}
                size={20}
                color={isLinked(ing._lid) ? colors.primary : colors.textMuted}
              />
              <Text style={[styles.browseName, isLinked(ing._lid) && { color: colors.primary }]}>
                {amountLabel(ing) ? `${amountLabel(ing)} ` : ''}{ing.name}
              </Text>
              <Text style={[styles.status, isLinked(ing._lid) && styles.statusActive]}>{statusOf(ing)}</Text>
            </TouchableOpacity>
          ))}
        </View>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  sil: { paddingLeft: 20, marginTop: spacing.sm },
  label: { fontSize: 11, fontWeight: '600', letterSpacing: 0.5, textTransform: 'uppercase', color: colors.textMuted, marginBottom: 6 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, alignItems: 'center', minHeight: 28 },
  linkedChip: { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: colors.primary + '1A', borderRadius: 14, paddingHorizontal: 8, paddingVertical: 3 },
  linkedText: { color: colors.primary, fontSize: 12, fontWeight: '600' },
  amount: { color: colors.primary, opacity: 0.6, fontSize: 11 },
  empty: { fontSize: 12, fontStyle: 'italic', color: colors.textMuted },
  addChip: { flexDirection: 'row', alignItems: 'center', gap: 3, borderWidth: 1, borderColor: colors.border, borderRadius: 14, paddingHorizontal: 8, paddingVertical: 3 },
  addChipHot: { borderColor: colors.warning },
  addText: { fontSize: 12, color: colors.text },
  doneRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  doneText: { fontSize: 12, color: colors.success },
  browseBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: spacing.sm },
  browseBtnText: { fontSize: 12, color: colors.textMuted },
  browseCard: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, padding: spacing.sm, marginTop: 6 },
  browseRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingVertical: 6 },
  browseName: { flex: 1, fontSize: 13, color: colors.text },
  status: { fontSize: 11, color: colors.textMuted },
  statusActive: { color: colors.primary },
});

// client/src/components/StepIngredientLinker.vue
<script setup>
import { ref, computed } from 'vue';

const props = defineProps({
  modelValue:      { type: Array,  default: () => [] },    // _lid[] linked to this step
  ingredients:     { type: Array,  required: true },       // all recipe ingredients (with _lid)
  assignmentsById: { type: Object, default: () => ({}) },  // _lid -> step numbers (1-based)
  stepNumber:      { type: Number, required: true },
  stepText:        { type: String, default: '' },
});
const emit = defineEmits(['update:modelValue']);

const showBrowse  = ref(false);
const searchQuery = ref('');

const byId = computed(() =>
  Object.fromEntries(props.ingredients.map(i => [i._lid, i]))
);

const linked = computed(() =>
  props.modelValue.map(lid => byId.value[lid]).filter(Boolean)
);

const unassigned = computed(() =>
  props.ingredients.filter(i => (props.assignmentsById[i._lid]?.length ?? 0) === 0)
);

function rootWords(name) {
  return String(name)
    .toLowerCase()
    .replace(/\(.*?\)/g, '')
    .split(/\s+/)
    .filter(w => w.length > 2);
}

function isMentioned(ing) {
  const text = props.stepText.toLowerCase();
  return rootWords(ing.name).some(w => text.includes(w));
}

const unassignedSorted = computed(() =>
  [...unassigned.value].sort((a, b) => Number(isMentioned(b)) - Number(isMentioned(a)))
);

const browseList = computed(() => {
  const q = searchQuery.value.toLowerCase().trim();
  return q
    ? props.ingredients.filter(i => i.name.toLowerCase().includes(q))
    : props.ingredients;
});

function isLinked(lid) {
  return props.modelValue.includes(lid);
}

function amountLabel(ing) {
  return [ing.amount, ing.unit].filter(Boolean).join(' ');
}

function statusOf(ing) {
  const steps = props.assignmentsById[ing._lid] || [];
  if (isLinked(ing._lid)) {
    const others = steps.filter(s => s !== props.stepNumber);
    return others.length ? `also step ${others.join(', ')}` : 'in this step';
  }
  return steps.length ? `step ${steps.join(', ')}` : 'unassigned';
}

function link(lid) {
  if (!props.modelValue.includes(lid))
    emit('update:modelValue', [...props.modelValue, lid]);
}
function unlink(lid) {
  emit('update:modelValue', props.modelValue.filter(x => x !== lid));
}
function toggle(lid) {
  isLinked(lid) ? unlink(lid) : link(lid);
}
</script>

<template>
  <div class="sil">
    <!-- Zone 1: linked ingredients -->
    <div class="sil-label">In this step</div>
    <div class="sil-chips">
      <v-chip
        v-for="ing in linked"
        :key="ing._lid"
        color="primary"
        variant="tonal"
        size="small"
        closable
        :aria-label="`Remove ${ing.name} from this step`"
        @click:close="unlink(ing._lid)"
      >
        <span v-if="amountLabel(ing)" class="sil-amount">{{ amountLabel(ing) }}</span>
        {{ ing.name }}
      </v-chip>
      <span v-if="!linked.length" class="sil-empty">Nothing linked yet</span>
    </div>

    <!-- Zone 2: unassigned worklist -->
    <div class="sil-label mt-3">Unassigned</div>
    <div class="sil-chips">
      <template v-if="unassigned.length">
        <v-chip
          v-for="ing in unassignedSorted"
          :key="ing._lid"
          :color="isMentioned(ing) ? 'warning' : undefined"
          variant="outlined"
          size="small"
          :aria-label="`Add ${ing.name} to this step`"
          class="sil-addable"
          @click="link(ing._lid)"
        >
          <template #prepend>
            <v-icon size="14" class="mr-1">
              {{ isMentioned(ing) ? 'mdi-creation' : 'mdi-plus' }}
            </v-icon>
          </template>
          {{ ing.name }}
        </v-chip>
      </template>
      <span v-else class="sil-done">
        <v-icon size="16" color="success" class="mr-1">mdi-check-circle</v-icon>
        Every ingredient is used in a step
      </span>
    </div>

    <!-- Zone 3: browse all -->
    <div class="mt-3">
      <v-btn
        variant="text"
        size="x-small"
        density="compact"
        :prepend-icon="showBrowse ? 'mdi-chevron-up' : 'mdi-magnify'"
        class="sil-browse-btn"
        @click="showBrowse = !showBrowse"
      >
        Browse all ingredients
      </v-btn>

      <v-expand-transition>
        <v-card v-show="showBrowse" variant="outlined" class="mt-2">
          <v-text-field
            v-model="searchQuery"
            density="compact"
            variant="outlined"
            hide-details
            prepend-inner-icon="mdi-magnify"
            placeholder="Search…"
            aria-label="Search all ingredients"
            class="ma-2"
          />
          <v-list density="compact" class="py-0">
            <v-list-item
              v-for="ing in browseList"
              :key="ing._lid"
              :aria-label="`${isLinked(ing._lid) ? 'Remove' : 'Add'} ${ing.name}`"
              class="sil-browse-row"
              @click="toggle(ing._lid)"
            >
              <template #prepend>
                <v-icon :color="isLinked(ing._lid) ? 'primary' : undefined" size="20">
                  {{ isLinked(ing._lid) ? 'mdi-checkbox-marked' : 'mdi-checkbox-blank-outline' }}
                </v-icon>
              </template>
              <template #title>
                <span :class="{ 'text-primary': isLinked(ing._lid) }">
                  <span v-if="amountLabel(ing)" class="sil-amount">{{ amountLabel(ing) }}</span>
                  {{ ing.name }}
                </span>
              </template>
              <template #append>
                <span class="sil-status" :class="{ 'sil-status--active': isLinked(ing._lid) }">
                  {{ statusOf(ing) }}
                </span>
              </template>
            </v-list-item>
          </v-list>
        </v-card>
      </v-expand-transition>
    </div>
  </div>
</template>

<style scoped>
.sil {
  padding-left: 28px;
}
.sil-label {
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  opacity: 0.55;
  margin-bottom: 6px;
}
.sil-chips {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  align-items: center;
  min-height: 28px;
}
.sil-amount {
  opacity: 0.6;
  font-size: 11px;
  margin-right: 4px;
}
.sil-empty {
  font-size: 12px;
  font-style: italic;
  opacity: 0.45;
}
.sil-done {
  display: inline-flex;
  align-items: center;
  font-size: 12px;
  color: rgb(var(--v-theme-success));
}
.sil-addable {
  cursor: pointer;
}
.sil-browse-btn {
  opacity: 0.6;
}
.sil-browse-btn:hover {
  opacity: 1;
}
.sil-browse-row {
  cursor: pointer;
}
.sil-status {
  font-size: 11px;
  opacity: 0.5;
}
.sil-status--active {
  color: rgb(var(--v-theme-primary));
  opacity: 1;
}
</style>
